#!/bin/bash
#local_path=$(dirname "$0")
local_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
local_path=${local_path%'/bin'}
#echo $local_path
#remote_path=`echo $local_path | grep mnt`
except=( 'service' '--start' '--stop' '--status' '--restart' )
len=${#except[*]}
#i=0
flag=0
set +
if [[ $# = 0 ]]; then
    echo 'Error: No argument is provided'
    exit
fi
while [[ $i -lt $len ]]
do
    if [[ $1 = ${except[$i]} ]]; then
        flag=1
        break
    fi
    let i++
done
#result=$(${local_path}/_src/rackhd-cli/rackhd $*)
if [[ ${local_path} = '/home/vagrant' ]]; then
    local_path='/mnt/krein' ## For remote mount usage on physical stack
fi
if [[ $flag = 1 ]]; then
    sudo ${local_path}/_src/rackhd-cli/rackhd $*
else
    result=$(${local_path}/_src/rackhd-cli/rackhd $*)
    exit_status=$?
    if [[ $exit_status = 0 ]]; then
        json_result=$(echo $result | python -mjson.tool)
        json_status=$?
        if [[ "$json_status" = "0" ]]; then
            echo -n $result | python -mjson.tool
        else
            echo -n $result
        fi
    else
        echo $result
    fi
fi
set -
