#!/bin/bash
#Program:
#    This program is used to send IPMI commands for Intel servers
#    Below commands are supported
#    -p ipaddress: power cycle
#    -on ipaddress: power on a node
#    -off ipaddress: power off a node
#    -fru ipaddress: get fru information
#    -s ipaddress: get nodes power status
#History:
#    Created on 20150823
USERNAME=vagrant
PASSWORD=vagrant

if [ $# = 1 ]; then
    IP="192.168.128.$1"
else
    while getopts 'A:u:p:v:' OPT; do
        case $OPT in
            A)
                IP=$OPTARG
                #STACK_IP=$IP
                #BMC_IP="192.168.188.$IP"
                ;;
            v)
                USERNAME='vagrant'
                PASSWORD='vagrant'
                IP="192.168.128.$OPTARG"
                ;;
            u)
                USERNAME="$OPTARG"
                ;;
            p)
                PASSWORD=$OPTARG
                ;;
            ?)
                echo "Invalide parameter $1"
                exit0
        esac
    done
fi
echo $IP $USENAME $PASSWORD
ssh-keygen -f "/home/onrack/.ssh/known_hosts" -R $IP

~/bin/.script/expect_ssl $IP $USERNAME $PASSWORD


